# Generated by Django 4.0 on 2025-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
